# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


development:
  adapter: sqlserver
  username: sa
  password: '123'
  host: localhost
  database: blog

test:
  adapter: sqlserver
  username: sa
  password: '123'
  host: localhost
  database: blog

production:
  adapter: sqlserver
  username: sa
  password: '123'
  host: localhost
  database: blog
